### ISSUE TITLE
Fullcontrol path requests has waypoints with wrong yaw values

### ISSUE THREAD

**Issue by idkwhatmyid** [open-rmf/rmf_ros2#177]
When x coordinates of consecutive waypoints are decreasing the yaw value is always 0.0 but it needs to face the other direction (3.14). The same goes for decreasing y coordinates where it is 1.57 but needs to be -1.57. I also notice robot spins to 0.0 degrees infront of the doors. What node is providing the yaw values in the `robot_path_requests` messages?

```
path:
- t:
    sec: 1851
    nanosec: 745000000
  x: 48.25251388549805
  y: -19.186559677124023
  yaw: 1.5216608047485352
  obey_approach_speed_limit: false
  approach_speed_limit: 0.0
  level_name: L1
  index: 0
- t:
    sec: 1852
    nanosec: 42178250
  x: 48.25251388549805
  y: -19.186559677124023
  yaw: 1.5658183097839355
  obey_approach_speed_limit: false
  approach_speed_limit: 0.0
  level_name: L1
  index: 0
- t:
    sec: 1856
    nanosec: 579068139
  x: 48.242881774902344
  y: -21.121646881103516
  yaw: 1.5658183097839355
  obey_approach_speed_limit: false
  approach_speed_limit: 0.0
  level_name: L1
  index: 0
- t:
    sec: 1859
    nanosec: 465962349
  x: 48.242881774902344
  y: -21.121646881103516
  yaw: 0.013681734912097454
  obey_approach_speed_limit: false
  approach_speed_limit: 0.0
  level_name: L1
  index: 0
- t:
    sec: 1869
    nanosec: 817861630
  x: 43.40037155151367
  y: -21.15367317199707
  yaw: 0.013681734912097454
  obey_approach_speed_limit: false
  approach_speed_limit: 0.0
  level_name: L1
  index: 0
- t:
    sec: 1870
    nanosec: 62518684
  x: 43.40037155151367
  y: -21.15367317199707
  yaw: -0.016246803104877472
  obey_approach_speed_limit: false
  approach_speed_limit: 0.0
  level_name: L1
  index: 0
task_id: '1473'
```
The robot appears to  spin randomly at turning points and in front of doors. We are using ROS2 free_fleet and Nav2. Can someone help to fix this behaviour? Thanks.
