### ISSUE TITLE
Cannot change robot speed on different lanes

### ISSUE THREAD

**Issue by BaraOilBalm** [open-rmf/rmf_ros2#234]
Hi
I am trying to change the speed of the robot when passing different lanes. I have set the speed of lanes on traffic-editor. My robot is using free_fleet_client to receive data from free_fleet_server.

```
      - [216, 215, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0.5]}]
      - [186, 215, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0.5]}]
      - [215, 198, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0.5]}]
      - [212, 186, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0.3]}]
      - [197, 220, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [220, 187, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [217, 188, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [188, 220, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [200, 187, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]
      - [212, 221, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0.5]}]
      - [221, 216, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0.5]}]
      - [221, 187, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], orientation: [1, ""], speed_limit: [3, 0]}]

```

When viewing the /fleet_state as the robot passes the lanes, there is no change in the obey_approach_speed_limit message and approach_speed_limit message. Is there a way to allow robot to change speed as it passes lanes with different speed_limit?

```
  task_id: '302'
  seq: 0
  mode:
    mode: 2
    mode_request_id: 0
  battery_percent: 99.0
  location:
    t:
      sec: 369
      nanosec: 920000000
    x: 43.530635833740234
    y: -19.39431381225586
    yaw: -1.8339184522628784
    obey_approach_speed_limit: false
    approach_speed_limit: 0.0
    level_name: L1
    index: 0
  path:
  - t:
      sec: 368
      nanosec: 3149896
    x: 43.351749420166016
    y: -19.40717124938965
    yaw: -1.5812199115753174
    obey_approach_speed_limit: false
    approach_speed_limit: 0.0
    level_name: L1
    index: 0
  - t:
      sec: 371
      nanosec: 551502622
    x: 43.33673095703125
    y: -20.847936630249023
    yaw: -1.5812199115753174
    obey_approach_speed_limit: false
    approach_speed_limit: 0.0
    level_name: L1
    index: 0
  - t:
      sec: 374
      nanosec: 485743624
    x: 43.33673095703125
    y: -20.847936630249023
    yaw: -0.0006752533954568207
    obey_approach_speed_limit: false
    approach_speed_limit: 0.0
    level_name: L1
    index: 0
  - t:
      sec: 385
      nanosec: 86780916
    x: 48.303916931152344
    y: -20.851289749145508
    yaw: -0.0006752533954568207
    obey_approach_speed_limit: false
    approach_speed_limit: 0.0
    level_name: L1
    index: 0
```
